### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Htorne** [Almamu/EVESharp#11]
**Describe the bug**
Launching a node for the first time. 

**To Reproduce**
Followed the guide 

**Expected behavior**
Unsure

**Environment information:**
Windows Server 2019 Standard
Visual Studio 2019 

**Additional context**
![image](https://user-images.githubusercontent.com/6929271/111174519-c967fc80-85a7-11eb-8bc8-bedd53a2659e.png)

**Comment by Almamu** [comment]
Can you try with the commit I just pushed? Should fix the issue.

Looks like on commit e0501d0912b70f12fdb0f734260a475c1c204718 I slipped a change that is meant to be pushed when the marketProxy is completely written

**Comment by Htorne** [comment]
It works, very nice thanks. I'm very excitet to drive deep into the code :) thanks for your hard work.
