### ISSUE TITLE
[question] Adding last game client 1.22	Citadel

### ISSUE THREAD

**Issue by Metalica** [Almamu/EVESharp#14]
Adding support for Citadel before alpha and omega clones.

Release date: 27 April 2016

"Citadel introduced Upwell structures (new player owned stations referred to as citadels[46]), Force Auxiliaries (a new line of logistics themed capital ships), a rebalance of existing capital ships, new super-weapons for citadels and Titans, a unique citadel named the 'Palatine Keepstar', of which only one may exist in the game at any given time, and 'Recurring Opportunities' (a daily quest for bonus skill points feature, which have since been removed.).[47]

Citadel was the first major expansion to Eve Online since CCP made changes to their release cadence"

**Comment by Almamu** [comment]
This is not related to Apocrypha at all. EVESharp only aims to properly support apocrypha clients.

**Comment by Almamu** [comment]
Just to add to this, I have the feeling that you've mistaken EVESharp for https://github.com/EvEmu-Project/evemu_Crucible
