### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xxdolcexx** [Almamu/EVESharp#25]
**Describe the bug**
can't get proxy to run don't know what i do not good 
**To Reproduce**

![Untitled](https://user-images.githubusercontent.com/426979/173815288-5c9acd3c-2258-4742-9b65-feac68079b7d.png)

won't run

**Expected behavior**
cant get proxy to run
**Environment information:**
 - OS: windows

**Additional context**
Add any other context about the problem here. Sharing server and client logs are good additional context that might help trace the issue and fix it faster.

**Comment by Almamu** [comment]
Looks like you are running the server in single mode, not proxy mode. Moreover, the configuration for the Orchestrator is not right, check the appsettings.json and ensure that it has all the database settings properly configurated.
