### ISSUE TITLE
Account Creation

### ISSUE THREAD

**Issue by Fizabastion** [Almamu/EVESharp#4]
Had issues with account creation on both Windows 7 and Ubuntu 18.04 LTS  systems.   
first issue on the windows 7 was: 

EVESharp/ClusterController/Configuration/Configuration.cs
            FileIniDataParser parser = new FileIniDataParser();  
I had to change to:
            var parser = new FileIniDataParser();
to get the server to even get into the listen mode.
even after that it does not seem to want to read in the configuration.conf autoaccount value so had to do a workaround and change:
EVESharp/ClusterController/Configuration/Authentication.cs
             this.Autoaccount = false;
I had to change to:
             this.Autoaccount = true;
on both machines...  I know thats not way was intended to work, but allows me in the character creation.

So far I like how you are going on this, and wish to say thank you for all your hard work.

**Comment by Almamu** [comment]
That's a weird situation. What IDE are you using on both systems? I'd like to reproduce the issue so I can debug it, none of my machines have any issue running the server (Arch and Windows 10).

**Comment by Fizabastion** [comment]
on Windows 7 I am using Visual Studio 2019
on Ubuntu 18.04 LTS I am using Mono Devel

**Comment by Almamu** [comment]
Okay, I'll setup some test environments and try to reproduce the errors with the OS and IDE combination. I'll get back to you in a couple of hours at best.

**Comment by Almamu** [comment]
I've tried a couple different machines with the setups you said but I cannot find any issue similar to what you describe, I did find some issues on the account table that need addressing, but I don't think It's related to the issue you're having. Do you have any screenshots/logs of the errors?

**Comment by Fizabastion** [comment]
I will give you more info in a bit, gotta take care of rl stuff then be back able to do things

**Comment by Fizabastion** [comment]
Error on Ubuntu 18.04 LTS:
3/18/20 7:40 PM D 192.168.1.8: Received QueueCheck command
3/18/20 7:40 PM D 192.168.1.8: Sending LowLevelVersionExchange...
3/18/20 7:41 PM D 192.168.1.8: Received VipKey command
3/18/20 7:41 PM D 192.168.1.8: Received correct Crypto request
3/18/20 7:41 PM T 192.168.1.8: Rejected by server; requesting plain password
3/18/20 7:41 PM D LoginQueue: Processing login for Testplayer
3/18/20 7:41 PM T LoginQueue: : Rejected by database
-----
configuration.conf:
[database]
username=evesharp
password=***
hostname=localhost
name=evedb
autoaccount=true
role=ROLE_PLAYER

[logfile]
directory=logs
logfile=ClusterController.log
----------------------

Error Windows 7:
3/18/20 8:00 PM D 192.168.1.3: Received QueueCheck command
3/18/20 8:00 PM D 192.168.1.8: Sending LowLevelVersionExchange...
3/18/20 8:01 PM D 192.168.1.8: Received VipKey command
3/18/20 8:01 PM D 192.168.1.8: Received correct Crypto request
3/18/20 8:01 PM T 192.168.1.8: Rejected by server; requesting plain password
3/18/20 8:01 PM D LoginQueue: Processing login for Testplayer
3/18/20 8:01 PM T LoginQueue: : Rejected by database
3/18/20 8:01 PM E 192.168.1.8: A request to send or receive data was dissallowed becasue the socket had already been shut down in that direction with a previous shutdown call
3/18/20 8:04 PM T 192.168.1.8:      at System.Net.Sockets.Socket.BeginReceive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, AsyncCallback callback, Object state)     at Common.Netword.EVEClientSocket.BeginReceive(Byte[] buffer, AsyncCallback callback) in C:\Users\user\Downloads\EVESharp-master\EVESharp-master\Server\Common\Network\EVEClientSocket.cs:line 129
----
configuration.conf:

[database]
username=evedb
password=***
hostname=localhost
name=evedb
autoaccount=true
role=ROLE_PLAYER

[logfile]
directory=logs
logfile=ClusterController.log

**Comment by Fizabastion** [comment]
btw: I did a full git clone and download on both systems compiled and then ran, so it was fresh

**Comment by Almamu** [comment]
The configuration files are wrong, the autoaccount configuration is an ini section, like this:
```
[autoaccount]
enabled=true
role=ROLE_PLAYER
```

This way it should work properly.

**Comment by Fizabastion** [comment]
okay, thanks kindly for your assistance
