### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Invictus79** [Almamu/EVESharp#6]
First of all great work. Got the server running. Took a few hours but all was fine. 

Now i can log in. create users etc. that works excellent. 
Is it correct that character creation is not working. (when i create character it says creating character but stays on char creation) 
When i look into the Db there is no new entry. 

I tried to put my userID to a preexistent entry but then the client gets stuck at character selection.

**Comment by Almamu** [comment]
There is no support for Character creation yet (that implies no character selection either), that's the next logical step, although there's other things keeping me busy from working on this.

**Comment by Invictus79** [comment]
Hi, Thanks for the update,
Now I'm sure i did the install right :) . And again good work am impressed.

Op do 29 okt. 2020 om 11:53 schreef Alexis Maiquez <notifications@github.com
