### ISSUE TITLE
[question] Unable to start ClusterController.exe

### ISSUE THREAD

**Issue by Taspyr** [Almamu/EVESharp#9]
**Describe the bug**
Trying to start ClusterControler. Starts without any output. Seems to be crashed? Because I'm trying to start Node after and it's unable to connect to proxy.

**To Reproduce**
1. Try to start the ClusterController.exe
2. See an empty command promt for a moment and see it's closed

**Expected behavior**
ClusterController.exe starts with a correct output.

**Environment information:**
 - OS: Win 10
 - IDE: MVS 19

**Comment by Almamu** [comment]
Can you please share the configuration for both Node and ClusterController? Also ensure there's nothing listening on port 26000 which is the default port for the game servers.

It might help to run the server from the IDE or from a CMD session so you see the full output if it crashes (like any exception being thrown).

**Comment by Taspyr** [comment]
Configuration for ClusterController:
[database]
username=evesharp
password=evesharp
hostname=localhost
name=evedb

[logfile]
directory=logs
logfile=ClusterController.log

[autoaccount]
enabled=true
role=ROLE_PLAYER, ROLE_LOGIN, ROLE_ADMIN, ROLE_QA, ROLE_SPAWN,

[listening]
port=26000

Configuration for Node:
[database]
username=evesharp
password=evesharp
hostname=localhost
name=evedb

[proxy]
hostname=127.0.0.1
port=26000

[authentication]
loginMessageType=MESSAGE
loginMessage=Welcome to EVESharp Debug Build

[logfile]
directory=logs
logfile=ClusterController.log

They are in folders with executables like
.\Server\ClusterController\bin\Debug\netcoreapp3.1 and
.\Server\Node\bin\Debug\netcoreapp3.1 respectively.

How would I ensure that nothing is listening on 26000?

сб, 13 февр. 2021 г. в 17:00, Alexis Maiquez <notifications@github.com>:

**Comment by Taspyr** [comment]
By the way, exception says about unknown role value:

System.Exception: Unknown role value
   at ClusterController.Configuration.Authentication.Load(KeyDataCollection
section) in
C:\Users\TanJala\Desktop\EVESharp-master\Server\ClusterController\Configuration\Authentication.cs:line
39
   at Configuration.General.LoadFromFile(String filename, Container
container) in
C:\Users\TanJala\Desktop\EVESharp-master\Server\ClusterController\Configuration\Configuration.cs:line
27
   at ClusterController.Program.Main(String[] args) in
C:\Users\TanJala\Desktop\EVESharp-master\Server\ClusterController\Program.cs:line
74

сб, 13 февр. 2021 г. в 17:00, Alexis Maiquez <notifications@github.com>:

**Comment by Almamu** [comment]
I've uploaded a commit that should fix the issue. The problem is with the role list interpreting the last comma as an empty role name and thus refusing to load. Please let me know if that fixed the issue ;)

**Comment by Taspyr** [comment]
Yeah, it fixed the issue, so both Node and ClusterController start normally.

сб, 13 февр. 2021 г. в 21:39, Alexis Maiquez <notifications@github.com>:
